[package]
name = "tasker"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version="1.0.228", features=["derive"] }
serde_json = "1.0"
comfy-table = "7.2.1"
clap = { version="4.5.53", features=["derive"] }
time = { version="0.3.44", features=["serde", "serde-well-known", "macros"] }
